### ISSUE TITLE
OLED mis config.

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/oled_display_node#16]
hostname -I | cut -f 1 -d' '

Is how the oled display .cpp gets it's IP.  If there is a LS-LIDAR in the mix, this is the first IP it sees, and not the WiFI hostname IP.

So a Magni with a LS-Lidar will show the IP of the configured lidar, not the hostname, what's worse the wrong IP will persist, even if the lidar is disconnected.

**Comment by mjstn** [comment]
I am closing this because it is better addressed in issue 18 so this is a duplicate.  Plus I have a change that may fix this.
