### ISSUE TITLE
In new noetic image battery_state not reporting

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/oled_display_node#19]
Since enabling the lidar in ethernet,  battery topic is empty, I am pretty sure it was reporting before.

**Comment by mjstn** [comment]
I have the early feb noetic image and am regression testing a bunch of OLED node fixes/additions.  
Can you explain what I should do Alan to replicate your observation here?  I have a LiShan and can plug it in but where is the 'enabling' done please.   Thanks

**Comment by mjstn** [comment]
This issue needs to be in pi_image, not here.   OLED node can do nothing if /battery_state is not present.

**Comment by mjstn** [comment]
I am assigning this to Alan so he can then move it to pi image and this one should go away.

**Comment by anfederman** [comment]
Motor state active is now working.  IP still incorrect if LS Lidar installed.
