### ISSUE TITLE
error build (catkin build)

### ISSUE THREAD

**Issue by PedroDesRobots** [UbiquityRobotics/oled_display_node#4]
Just to inform you.
I got this error during build time (ubuntu 16.04 - ROS Kinetic) :
 ```
/home/user/catkin_ws/src/oled_display_node/src/oled_display_node.cpp:169:1: error: "/*" within comment [-Werror=comment]
 /*
```
I just remove the "/" at ligne 169 in cpp file, then it was fixed.
I know that it's a minor bug.. but just to know.

Best.

**Comment by PedroDesRobots** [comment]
This error didn't happen on a fresh docker with ROS Kinetic installed.. It should come from my local machine.. sorry for opened this issue.

**Comment by rohbotics** [comment]
Re-opening this because it is such a easy fix for any potential frustation that other users might face.

**Comment by rohbotics** [comment]
Ok I fixed this, thanks for the report.

Good luck on your project!
