### ISSUE TITLE
Seems to be an incomplete initialization leads to bad display

### ISSUE THREAD

**Issue by mjstn** [UbiquityRobotics/oled_display_node#6]
Sometimes the display does not come up properly.
It can show up in assorted ways from inverse video on some lines to different text and other problems.

Also we should back out periodic ros log of battery voltage as that is really a higher level functionality.
We will continue to show battery voltage if we are a magni but will not also generate a ros log. That is being added to motor_node where it should be located.

My theory is the initialization we do is not sufficient to guarentee proper mode setup.

**Comment by MoffKalast** [comment]
We got the same results when testing it out a few months back as well. The text can be missing a few lines, only display a few chars, sometimes half a word, and on occasion it works perfectly.

**Comment by mjstn** [comment]
A more through set of initialization parameters is being sent to the display as of 16 days agoe in commit 37b6cf376621bab1ed3b7f33a48a0911f9e0745b.       I have seen this to fix at least the display i had that was showing badly.

**Comment by mjstn** [comment]
Several changes have happened since this defect including a refactor to support to different display types.   I am closing this issue for lack of it being seen since assorted fixes were done since time of this issue being reported
